BASE: ['']
TOOLBOX_MODE: "only_test"   # "train_and_test" or "only_test" 
TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 10     # Adjust as needed (e.g., 30)
  LR: 3e-4
  MODEL_FILE_NAME: PURE_PURE_PURE_RGBMamba_miniA  # Adjust if desired
  AUG: 1
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False       # If first time, should be True
    DATA_FORMAT: NDCHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"  # Update as needed
    CACHED_PATH: "/content/drive/MyDrive/DDCache/RGBMamba"               # Update as needed
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"
    CACHED_PATH: "/content/drive/MyDrive/DDCache/RGBMamba"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR']
  USE_LAST_EPOCH: False  # If False, uses the best epoch found via validation
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"
    CACHED_PATH: "/content/drive/MyDrive/DDCache/RGBMamba"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
DEVICE: "cuda:0"
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: "runs/exp"
MODEL:
  DROP_RATE: 0.2
  NAME: RGBMamba_miniA  # IMPORTANT: name of the combined model
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"      # or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: "/content/drive/MyDrive/DDCache/RGBMamba/TrainedModels/PURE_SizeW128_SizeH128_ClipLength160_DataTypeStandardized_DataAugNone_LabelTypeStandardized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/PURE_PURE_PURE_RGBMamba_miniA_Epoch7.pth"  # Optional: path to a saved model for "only_test" mode
